name: Build & Release Installers

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-installers:
    name: Build Windows Installer
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clone Maven Dependency
        uses: actions/checkout@v4
        with:
          repository: Kakifrucht/yetanotherhueapi
          path: yetanotherhueapi_repo

      - name: Install Maven Dependency
        working-directory: yetanotherhueapi_repo
        shell: bash
        run: |
          echo "Building and installing dependency to Maven Local..."
          mvn install
          echo "Dependency installed successfully."

      - name: Build with Gradle
        run: .\gradlew.bat jpackage -Pwindows-msi

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightBeat-${{ github.ref_name }}-Windows
          path: build/jpackage/LightBeat-*.msi

  create-release:
    name: Create GitHub Release
    needs: build-installers
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: installers/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            installers/LightBeat-${{ github.ref_name }}-Windows/*
