name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-fat-jar:
    name: Build Fat JAR
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clone Maven Dependency
        uses: actions/checkout@v4
        with:
          repository: Kakifrucht/yetanotherhueapi
          path: yetanotherhueapi_repo

      - name: Install Maven Dependency
        working-directory: yetanotherhueapi_repo
        run: |
          echo "Building and installing dependency to Maven Local..."
          mvn install -DskipTests
          echo "Dependency installed successfully."

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Fat JAR with Gradle
        run: ./gradlew clean shadowJar

      - name: Upload Fat JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhotonJockey-JAR
          path: build/libs/PhotonJockey-*.jar

  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clone Maven Dependency
        uses: actions/checkout@v4
        with:
          repository: Kakifrucht/yetanotherhueapi
          path: yetanotherhueapi_repo

      - name: Install Maven Dependency
        working-directory: yetanotherhueapi_repo
        shell: bash
        run: |
          echo "Building and installing dependency to Maven Local..."
          mvn install -DskipTests
          echo "Dependency installed successfully."

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Build Windows Installer with Gradle
        run: .\gradlew.bat clean jpackage -Pwindows-msi

      - name: Upload Windows Installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhotonJockey-Windows-Installer
          path: build/jpackage/PhotonJockey-*.msi

  create-release:
    name: Create GitHub Release
    needs: [build-fat-jar, build-windows-installer]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            release-assets/PhotonJockey-JAR/*
            release-assets/PhotonJockey-Windows-Installer/*
