name: Build and Upload Release Assets

on:
  release:
    types: [created]

jobs:
  build-fat-jar:
    name: Build Fat JAR (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clone Maven Dependency
        uses: actions/checkout@v4
        with:
          repository: Kakifrucht/yetanotherhueapi
          path: yetanotherhueapi_repo

      - name: Install Maven Dependency
        working-directory: yetanotherhueapi_repo
        run: |
          echo "Building and installing dependency to Maven Local..."
          mvn install -DskipTests
          echo "Dependency installed successfully."

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean test shadowJar

      - name: Get the project version
        id: get_version
        run: echo "VERSION=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Upload Fat JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/LightBeat-${{ steps.get_version.outputs.VERSION }}.jar

  build-windows-msi:
    name: Build Windows MSI Installer
    runs-on: windows-latest
    permissions:
      contents: write # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clone Maven Dependency
        uses: actions/checkout@v4
        with:
          repository: Kakifrucht/yetanotherhueapi
          path: yetanotherhueapi_repo

      - name: Install Maven Dependency
        working-directory: yetanotherhueapi_repo
        shell: bash
        run: |
          echo "Building and installing dependency to Maven Local..."
          mvn install -DskipTests
          echo "Dependency installed successfully."

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Build and test with Gradle
        run: .\gradlew.bat clean test jpackageImage -Pwindows-msi=true

      - name: Get the project version
        id: get_version
        shell: bash
        run: echo "VERSION=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Upload Windows MSI to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/jpackage/LightBeat-${{ steps.get_version.outputs.VERSION }}.msi
